services:
  backend:
    container_name: solana-wallet-local-backend
    build: ./backend
    network_mode: "service:gluetun-mx"
    environment:
      - NODE_ENV=production
    depends_on:
      - gluetun-mx
    restart: unless-stopped

  frontend:
    container_name: solana-wallet-local-frontend
    build: ./frontend
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
