services:
  backend:
    container_name: solana-wallet-local-backend
    build: ./backend
      #network_mode: "service:gluetun-mx"
    environment:
      - NODE_ENV=production
        #depends_on:
        #gluetun-mx:
        #condition: service_healthy
    restart: unless-stopped

  frontend:
    container_name: solana-wallet-local-frontend
    build: ./frontend
    ports:
      - "37246:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
