services:
  backend:
    build: ./backend
    ports:
      - "49271:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "37246:3000"
    depends_on:
      - backend
    restart: unless-stopped
