services:
  backend:
    container_name: solana-wallet-local-backend
    build: ./backend
    ports:
      - "49271:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    container_name: solana-wallet-local-frontend
    network_mode: "service:gluetun-mx"
    build: ./frontend
    ports:
      - "37246:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
      - gluetun-mx
    restart: unless-stopped
