services:
  backend:
    container_name: solana-wallet-local-backend
    build: ./backend
    ports:
      - "44271:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    container_name: solana-wallet-local-frontend
    build: ./frontend
    ports:
      - "37246:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
